test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.aaee25fd688435d63ed304f418829e4e036004d5.name = "Upgrade from #8"